package com.sugarcrm.sugarcrm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.math.BigInteger;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.MessageDigest;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2 2012-02-29T17:35:38.024+01:00
 * Generated source version: 2.5.2
 * 
 */
public final class SugarsoapPortType_SugarsoapPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://www.sugarcrm.com/sugarcrm", "sugarsoap");

	private static final String USER_NAME = "admin";
	private static final String USER_PASSWORD = "admin";
	private static final String APPLICATION_NAME = Class.class.getName();

	private SugarsoapPortType_SugarsoapPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = Sugarsoap.WSDL_LOCATION;

		String userName = null;
		String password = null;
		String userId = null;
		String sessionID = null;
		
		/**
		if (args.length != 3) {
			System.err.println("Usage: java -jar SugarCRMCE64v4SOAPLibrary.jar {SugarCRM URL} {user name} {password}");
			System.exit(1);
		}
		*/
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		Sugarsoap ss = new Sugarsoap(wsdlURL, SERVICE_NAME);
		SugarsoapPortType port = ss.getSugarsoapPort();

		{
			System.out.println("SugarCRM Server Info...");
			System.out.println("Version " + port.getServerInfo().getVersion());
			System.out.println("Flavor " + port.getServerInfo().getFlavor());

		}
		
		/**
		 * Try to login on SugarCRM
		 * 
		 * 1) Prepare a MD5 hash password 
		 * 2) Prepare a User Auth object 
		 * 3) Execute login
		 */
		{
			System.out.println("Invoking login...");

			// 1. Prepare a MD5 hash password
			MessageDigest messageDiget = MessageDigest.getInstance("MD5");
			password = (args[2].isEmpty()) ? USER_PASSWORD : args[2];
			messageDiget.update(password.getBytes());

			// 2. Prepare a User Auth object
			com.sugarcrm.sugarcrm.UserAuth _login_userAuth = new UserAuth();
			userName = (args[1].isEmpty()) ? USER_NAME : args[1];
			_login_userAuth.setUserName(userName);
			_login_userAuth.setPassword((new BigInteger(1, messageDiget
					.digest())).toString(16));
			java.lang.String _login_applicationName = APPLICATION_NAME;
			com.sugarcrm.sugarcrm.NameValueList _login_nameValueList = new NameValueList();	
			
			try {
				// 3. Execute login
				com.sugarcrm.sugarcrm.EntryValue _login__return = port.login(
						_login_userAuth, _login_applicationName,
						_login_nameValueList);
				System.out.println("Login Successfully for " + userName);
				System.out.println("Your session Id: " + _login__return.getId());
				sessionID = _login__return.getId();
			} catch (Exception e) {
				System.err.println("Login failed. Message: " + e.getMessage());
				e.printStackTrace();
				System.exit(1);
			}
		}

		/**
		 * Get UserId from SessionID
		 */
		{
			System.out.println("Invoking getUserId...");			
			try {
				userId = port.getUserId(sessionID);
				System.out.println("Your UserId is: " + userId);
			} catch (Exception e) {
				System.err.println("Get UserId failed. Message: " + e.getMessage());
				e.printStackTrace();
				System.exit(1);
			}
		}

		/**
		 * Logout
		 */
		{
			System.out.println("Invoking logout...");
			try {
				port.logout(sessionID);
			} catch (Exception e) {
				System.out.println("Logout failed. Message: " + e.getMessage());
				e.printStackTrace();
				System.exit(1);
			}
		}
		
		System.exit(0);
	}

}
