package com.sugarcrm.sugarcrm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-02-29T17:35:38.102+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "sugarsoap", 
                  wsdlLocation = "http://localhost:8888/SugarCE-Full-6.4.0/service/v4/soap.php?wsdl&style=rpc&use=literal",
                  targetNamespace = "http://www.sugarcrm.com/sugarcrm") 
public class Sugarsoap extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.sugarcrm.com/sugarcrm", "sugarsoap");
    public final static QName SugarsoapPort = new QName("http://www.sugarcrm.com/sugarcrm", "sugarsoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/SugarCE-Full-6.4.0/service/v4/soap.php?wsdl&style=rpc&use=literal");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Sugarsoap.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8888/SugarCE-Full-6.4.0/service/v4/soap.php?wsdl&style=rpc&use=literal");
        }
        WSDL_LOCATION = url;
    }

    public Sugarsoap(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Sugarsoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sugarsoap() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sugarsoap(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sugarsoap(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Sugarsoap(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SugarsoapPortType
     */
    @WebEndpoint(name = "sugarsoapPort")
    public SugarsoapPortType getSugarsoapPort() {
        return super.getPort(SugarsoapPort, SugarsoapPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SugarsoapPortType
     */
    @WebEndpoint(name = "sugarsoapPort")
    public SugarsoapPortType getSugarsoapPort(WebServiceFeature... features) {
        return super.getPort(SugarsoapPort, SugarsoapPortType.class, features);
    }

}
